### ISSUE TITLE
Cannot Add Lodging or Dining to Collections

### ISSUE THREAD

**Issue by duggym122** [seanmorley15/AdventureLog#258]
### Bug Description
Attempting to add lodging or dining to a collection fails to open the edit/entry dialog
 
### Steps to Reproduce
* Create a collection
* Enter the collection
* Click the "+" button to add an item
* Attempt to select "Lodging" or "Dining"
  
### Expected Experience
* A modal should open to allow entering event data
 
### Actual Experience
* No actions occur (no browser console events either)

**Comment by seanmorley15** [comment]
This was fixed in #259. With the new adventure creation and edit modal, there is no longer a need for separate buttons to create a lodging or restaurant type, they are **now available for selection with the rest of the types**. These type are only available for selection when adding to a collection. They must be converted to visited or planned types to remove them from a collection.
Thanks for reporting this!
