### ISSUE TITLE
[BUG] Adventure or transportation not shown in itinerary unless previous days have data

### ISSUE THREAD

**Issue by stjeanp** [seanmorley15/AdventureLog#316]
**Describe the bug**
If I add an adventure to a collection, it will not show up in the itinerary unless the previous days have data. I have a trip that runs from 3/1/25 to 3/10/25. I add the outbound and return flights. Only the outbound flights show up in the timeline. If I add something to 3/9, it still doesn't show up. I have to populate every single day covered by the collection for all of the adventure/travel data to show up in the itinerary timeline.

**To Reproduce**
1. Create a collection with start date of 3/1/2025 and end date of 3/10/2025
2. Add outbound flight on 3/1/2025
3. Add return flight on 3/10/2025
4. Itinerary will not display the return flight, instead it says "Nothing planned for this day. Enjoy the journey!"

**Expected behavior**
All activities (flights, adventures, etc.) should be displayed on the itinerary timeline once they've been added to the collection.

**Screenshots**
![Screenshot 2024-09-16 at 3 50 16 PM](https://github.com/user-attachments/assets/48e3b8d7-9a59-491b-a74d-8a80c05f4483)

![Screenshot 2024-09-16 at 3 51 28 PM](https://github.com/user-attachments/assets/0a8b1905-2e12-4843-85ab-e1ed1278d107)

**Comment by seanmorley15** [comment]
Thanks so much for finding this! I was trying to figure out what the issue was for the longest time but I also realized that March 9th is Daylight Savings Time! The code did not account for this before and just did not work when a daylight savings time was included. The new fix uses all UTC timing and no longer creates the explained issue.
To see the new update run `docker compose pull && docker compose up -d`
I hope this helps, enjoy!

**Comment by stjeanp** [comment]
I just re-pulled and the events are now showing up. Thank you so much for the quick fix.

**Comment by seanmorley15** [comment]
No problem 😃
