### ISSUE TITLE
[BUG] Not seeing an image when acces the app from a public URL

### ISSUE THREAD

**Issue by mvs12** [seanmorley15/AdventureLog#372]
Not a bug, but a question. How to get the image URL right when using a public URL? I can see the image in an adventure, when acces the app in my private network. But when I acces the app from a public URL I cannot see the image.

I'm using HAProxy with Let's Encrypt to acces the app from a public URL.

My docker-compose file (simplified):

```
services:
  web:
    #build: ./frontend/
    environment:
      - PUBLIC_SERVER_URL=http://server:8000 # MOST DOCKER USERS WILL NOT NEED TO CHANGE THIS EVER EVEN IF YOU CHANGE THE OUTWARD PORT
      - ORIGIN=https://mydomain.duckdns.org
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - "8015:3000"
    depends_on:
      - server

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    environment:
      - PUBLIC_URL='http://192.168.1.10:8016' # Match the outward port, used for the creation of image urls
      - CSRF_TRUSTED_ORIGINS=http://192.168.1.10:8016,https://mydomain.duckdns.org # Comma separated list of trusted origins for CSRF
      - DEBUG=False
      - FRONTEND_URL='https://mydomain.duckdns.org' # Used for email generation. This should be the url of the frontend
      - DISABLE_REGISTRATION=True
    ports:
      - "8016:80"
```

My haproxy.cfg file (simplified):

```
frontend www-https
    use_backend mydomain if { hdr(host) -i mydomain.duckdns.org }

backend mydomain
    server mydomain 192.168.1.10:8015
```

**Comment by seanmorley15** [comment]
In order to ensure that the images can work outside if your local network, you should change the `PUBLIC_URL` to the exposed version of your server container. You will have to make a new entry for your backend container like this, changing names as needed
```
frontend www-https
    use_backend adventure-frontend if { hdr(host) -i adventurelog.duckdns.org }

backend adventure-frontend
    server adventure-frontend 192.168.1.10:8015

frontend www-https
    use_backend adventure-backend if { hdr(host) -i adventurelog-api.duckdns.org }

backend adventure-backend
    server adventure-backend 192.168.1.10:8016
```
Then you would change `PUBLIC_URL` to `https://adventurelog-api.duckdns.org`
Ensure that the file permissions are right and that `CSRF_TRUSTED_ORIGINS` contains all of the origins like `https://adventurelog-api.duckdns.org,https://adventurelog.duckdns.org,http://192.168.1.10:8016,http://192.168.1.10:8015`

Let me know if this helps!

**Comment by mvs12** [comment]
This is working, thank you!

**Comment by seanmorley15** [comment]
Glad it's working! 😃
