### ISSUE TITLE
[REQUEST] Soft Delete Database Records / Delete Confirmation

### ISSUE THREAD

**Issue by nebriv** [seanmorley15/AdventureLog#400]
**Is your feature request related to a problem? Please describe.**
Right now it is very difficult to inadvertently delete an item with a misclick. Especially on mobile, while a confirmation prompt would be useful it might also be be beneficial to implement a soft delete aspect within the database.

**Describe the solution you'd like**
Add a "deleted" field to each item in the database, the flag could be a datetime stamp that a cleanup job could run through on a schedule. This would allow an admin to undelete an item by clearing the "deleted" field. Alternatively this could be a boolean flag.

**Comment by seanmorley15** [comment]
I agree with this, there currently is a confirmation prompt but I will look into the effectiveness of a soft delete option as well.
![image](https://github.com/user-attachments/assets/0e0919a3-f5c6-4621-8cc8-75efca5e8716)
This might be easier to implement because I am planning to add a few other cron style tasks to run periodically for things like image cleanup.

**Comment by nebriv** [comment]
Ahh! Ok, the notes are just missing the confirmation prompt then.

**Comment by seanmorley15** [comment]
Got it, I can add this to the notes and other collection things like transportations!
