### ISSUE TITLE
[BUG] When adding transportation, save/submit button is called "Edit"

### ISSUE THREAD

**Issue by nebriv** [seanmorley15/AdventureLog#403]
**Describe the bug**
When adding a new transportation to a collection the save/submit button is labeled "Edit". This is a little confusing because I'm not editing, I'm of course making a new entry. Probably just a mislabel :)

![image](https://github.com/user-attachments/assets/12394298-c056-434f-9ec7-978793b32b17)

**Comment by seanmorley15** [comment]
Yes this is a bug. The same modal window is used for edit/save. These modals for both transportations and notes have not been updated since my beta release of AdventureLog so I think I am going to take the time to rework them completely too look like the design of the new adventure create/edit modals (fixing this in the process)!
Thanks!

**Comment by nebriv** [comment]
You bet! I haven't used Svelte or (embarrassingly TypeScript) at all, so I'm just poking through the source to "learn" my way though it. Hypothetically this could just be fixed here with just a change from .edit to .save (or whatever verb is consistent)?
 
[<button type="submit" class="btn btn-primary mr-4 mt-4">{$t('transportation.edit')}</button>](https://github.com/seanmorley15/AdventureLog/blob/f7742ca37db59372faa64b10c487742c0dec8dd3/frontend/src/lib/components/NewTransportation.svelte#L249)

**Comment by seanmorley15** [comment]
Yes! Also I just looked and it's actually easier. There is both a create and edit modal so it just requires one chance
